# Generated 2021-10-16 from:
# /workspace/yingzhi/speechbrain/recipes/IEMOCAP/emotion_recognition/hparams/train_with_wav2vec2.yaml
# yamllint disable
# ########################################
# Emotion recognition from speech using wav2vec2
#
#  * Authors: Yingzhi WANG
# ########################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1992
__set_seed: !apply:torch.manual_seed [1992]

# Dataset will be downloaded to the `data_original`
data_folder: /workspace/data/IEMOCAP/IEMOCAP_ahsn_leave-two-speaker-out-split1 # e.g, /workspace/data/IEMOCAP/IEMOCAP_ahsn_leave-two-speaker-out
output_folder: results/wav2vec2_base_fold_multitask_conv/1992
save_folder: results/wav2vec2_base_fold_multitask_conv/1992/save_unseenID_4outs_1
train_log: results/wav2vec2_base_fold_multitask_conv/1992/train_log.txt
output_log: results/wav2vec2_base_fold_multitask_conv/1992/output_log.txt
pretrain_path: /workspace/data_paper2/

# URL for the wav2vec2 model, you can change to benchmark diffrenet models
# Important: we use wav2vec2 base and not the fine-tuned one with ASR task
# This allow you to have ~4% improvment
wav2vec2_hub: facebook/wav2vec2-base

# different speakers for train, valid and test sets
# (more challenging exercise: higher error rate)
different_speakers: false

# Path where data manifest files will be stored
train_annotation: /ws/ifp-10_1/hasegawa/jialuli3/LB_new_firmware/json/combine_new_old/train_unseenID_1.json
valid_annotation: /ws/ifp-10_1/hasegawa/jialuli3/LB_new_firmware/json/combine_new_old/valid_unseenID.json
test_annotation: /ws/ifp-10_1/hasegawa/jialuli3/LB_new_firmware/json/combine_new_old/test_unseenID_1.json

# The train logger writes training statistics to a file, as well as stdout.
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: results/wav2vec2_base_fold_multitask_conv/1992/train_log.txt

ckpt_interval_minutes: 15 # save checkpoint every N min

# Training parameters
number_of_epochs: 25
lr: 0.0001
lr_wav2vec2: 0.00001

#whether to add triplet_loss
use_triplet_loss: false

# Model parameters
encoder_dim: 768
cnn_out_channels: 384 

dataloader_options:
  batch_size: 64
  shuffle: true
  num_workers: 2    # 2 on linux but 0 works on windows
  drop_last: false

# Wav2vec2 encoder
wav2vec2: &id001 !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
  source: facebook/wav2vec2-base
  output_norm: false
  freeze: false
  freeze_feature_extractor: false
  save_path: results/wav2vec2_base_fold_multitask_conv/1992/save_unseenID_4outs_1

avg_pool: !new:speechbrain.nnet.pooling.StatisticsPooling
  return_std: false

sp_cnn: &id_sp_cnn !new:speechbrain.lobes.models.convolution.ConvBlock
  num_layers: 1
  out_channels: !ref <cnn_out_channels>
  input_shape: [null,null,!ref <encoder_dim>]
  kernel_size: 1
  conv_module: !new:speechbrain.nnet.CNN.Conv1d
    input_shape: [null,null,!ref <encoder_dim>]
    out_channels: !ref <cnn_out_channels>  
    kernel_size: 1
  norm: !name:speechbrain.nnet.normalization.BatchNorm1d

chn_cnn: &id_chn_cnn !new:speechbrain.lobes.models.convolution.ConvBlock
  num_layers: 1
  out_channels: !ref <cnn_out_channels>
  input_shape: [null,null,!ref <encoder_dim>]
  kernel_size: 1
  conv_module: !new:speechbrain.nnet.CNN.Conv1d
    input_shape: [null,null,!ref <encoder_dim>]
    out_channels: !ref <cnn_out_channels>  
    kernel_size: 1
  norm: !name:speechbrain.nnet.normalization.BatchNorm1d

fan_cnn: &id_fan_cnn !new:speechbrain.lobes.models.convolution.ConvBlock
  num_layers: 1
  out_channels: !ref <cnn_out_channels>
  input_shape: [null,null,!ref <encoder_dim>]
  kernel_size: 1
  conv_module: !new:speechbrain.nnet.CNN.Conv1d
    input_shape: [null,null,!ref <encoder_dim>]
    out_channels: !ref <cnn_out_channels>  
    kernel_size: 1
  norm: !name:speechbrain.nnet.normalization.BatchNorm1d

man_cnn: &id_man_cnn !new:speechbrain.lobes.models.convolution.ConvBlock
  num_layers: 1
  out_channels: !ref <cnn_out_channels>
  input_shape: [null,null,!ref <encoder_dim>]
  kernel_size: 1
  conv_module: !new:speechbrain.nnet.CNN.Conv1d
    input_shape: [null,null,!ref <encoder_dim>]
    out_channels: !ref <cnn_out_channels>  
    kernel_size: 1
  norm: !name:speechbrain.nnet.normalization.BatchNorm1d

output_mlp_sp: &idsp !new:speechbrain.nnet.linear.Linear
  input_size: !ref <cnn_out_channels>
  n_neurons: 5
  bias: false

output_mlp_chn: &idchn !new:speechbrain.nnet.linear.Linear
  input_size: !ref <cnn_out_channels>
  n_neurons: 3
  bias: false

output_mlp_fan: &idfan !new:speechbrain.nnet.linear.Linear
  input_size: !ref <cnn_out_channels>
  n_neurons: 4
  bias: false

output_mlp_man: &idman !new:speechbrain.nnet.linear.Linear
  input_size: !ref <cnn_out_channels>
  n_neurons: 4
  bias: false

epoch_counter: &id006 !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: !ref <number_of_epochs>

modules:
  wav2vec2: *id001
  sp_cnn: *id_sp_cnn
  chn_cnn: *id_chn_cnn
  fan_cnn: *id_fan_cnn
  man_cnn: *id_man_cnn
  output_mlp_sp: *idsp
  output_mlp_chn: *idchn
  output_mlp_fan: *idfan
  output_mlp_man: *idman

model: &id003 !new:torch.nn.ModuleList
- [*idsp,*idchn,*idfan,*idman,*id_sp_cnn, *id_chn_cnn, *id_fan_cnn, *id_man_cnn]

log_softmax: !new:speechbrain.nnet.activations.Softmax
  apply_log: true

compute_cost: !name:speechbrain.nnet.losses.nll_loss

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
  metric: !name:speechbrain.nnet.losses.classification_error
    reduction: batch

error_stats_kic: !name:speechbrain.utils.metric_stats.KICMultitaskBinaryMetricStats

opt_class: !name:torch.optim.Adam
  lr: 0.0001

wav2vec2_opt_class: !name:torch.optim.Adam
  lr: 0.00001

lr_annealing: &id004 !new:speechbrain.nnet.schedulers.NewBobScheduler
  initial_value: 0.0001
  improvement_threshold: 0.0025
  annealing_factor: 0.9
  patient: 0

lr_annealing_wav2vec2: &id005 !new:speechbrain.nnet.schedulers.NewBobScheduler
  initial_value: 0.00001
  improvement_threshold: 0.0025
  annealing_factor: 0.9

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: results/wav2vec2_base_fold_multitask_conv/1992/save_unseenID_4outs_1
  recoverables:
    model: *id003
    wav2vec2: *id001
    lr_annealing_output: *id004
    lr_annealing_wav2vec2: *id005
    counter: *id006
